# Optimize store data management with Python

 ...
 
 <br></br>

 
 My mission is to ...
 
 <br></br>
 
 
<u> Summary</u> :
 
 1. Explore and clean <a href="https://github.com/donia-nefiz/Optimize-store-data-management-with-Python.git" target="_blank">BottleNeck datas</a>
     <br>*a. [erp.csv](http://localhost:8888/edit/erp.csv) : exploration and data cleaning [(here)](#another_cell_a)*</br>
     <br>*b. [web.csv](http://localhost:8888/edit/web.csv) : exploration and data cleaning [(here)](#another_cell_b)*</br>
     <br>*c. [liaison.csv](http://localhost:8888/edit/liaison.csv) : exploration and data cleaning [(here)](#another_cell_c)*</br>
     <br>*d. New df (merge) [(here)](#another_cell_d)*</br>

2. ...
<br></br>
    <br>A. ...</br>
    <br>*-- a.
    

*NB : this notebook is in english but all data are in french.*

## 1. BottleNeck data, files exploration and data cleaning

In [1]:
import pandas as pd

In [2]:
import numpy as np

  <a id='another_cell_a'></a>

### a. [erp.csv](http://localhost:8888/edit/erp.csv) : exploration and data cleaning

- Loading file:

In [3]:
erp = pd.read_csv('erp.csv', sep=';')

- First 5 rows display :

In [4]:
erp.head()

product_id  onsale_web  price  stock_quantity stock_status
0        3847           1   24.2               0   outofstock
1        3849           1   34.3               0   outofstock
2        3850           1   20.8               0   outofstock
3        4032           1   14.1               0   outofstock
4        4039           1   46.0               0   outofstock

- Number of rows and columns :

In [5]:
erp.shape

(825, 5)

- .dtypes display :

In [6]:
erp.dtypes

product_id          int64
onsale_web          int64
price             float64
stock_quantity      int64
stock_status       object
dtype: object

- "Valeur" columns .unique values display :

In [7]:
erp["product_id"].unique()

array([3847, 3849, 3850, 4032, 4039, 4040, 4041, 4042, 4043, 4045, 4046,
       4047, 4048, 4049, 4050, 4051, 4052, 4053, 4054, 4055, 4056, 4057,
       4058, 4059, 4060, 4062, 4063, 4064, 4065, 4066, 4067, 4068, 4069,
       4070, 4071, 4072, 4073, 4074, 4075, 4076, 4077, 4078, 4079, 4081,
       4083, 4084, 4085, 4086, 4087, 4090, 4092, 4094, 4095, 4096, 4097,
       4098, 4099, 4100, 4101, 4102, 4103, 4104, 4105, 4106, 4107, 4108,
       4115, 4130, 4132, 4137, 4138, 4139, 4141, 4142, 4144, 4146, 4147,
       4148, 4149, 4150, 4151, 4152, 4153, 4154, 4155, 4156, 4157, 4158,
       4159, 4160, 4161, 4162, 4163, 4164, 4165, 4166, 4167, 4168, 4170,
       4171, 4172, 4173, 4174, 4176, 4177, 4178, 4179, 4180, 4181, 4182,
       4183, 4186, 4187, 4188, 4190, 4191, 4192, 4193, 4194, 4195, 4196,
       4197, 4198, 4200, 4201, 4202, 4203, 4204, 4205, 4207, 4208, 4209,
       4210, 4211, 4212, 4213, 4215, 4216, 4217, 4219, 4220, 4221, 4222,
       4223, 4224, 4225, 4227, 4228, 4229, 4231, 42

In [8]:
erp["stock_status"].unique()

array(['outofstock', 'instock'], dtype=object)

In [9]:
erp["onsale_web"].unique()

array([1, 0], dtype=int64)

In [10]:
erp["price"].unique()

array([ 24.2 ,  34.3 ,  20.8 ,  14.1 ,  46.  ,  32.7 ,  31.2 ,  60.  ,
        42.6 ,  80.  ,  18.3 ,  22.8 ,  19.3 ,  21.8 ,   7.7 ,  33.7 ,
        44.3 ,  71.6 ,  86.1 ,  12.7 ,   8.7 ,  11.9 ,  14.5 ,  14.4 ,
        19.5 ,  22.  ,  16.6 ,  23.4 ,  33.2 ,  32.  ,  77.8 ,  14.7 ,
        14.05,  22.9 ,  44.  ,  37.  ,  39.  ,  17.  ,  23.2 ,  19.  ,
        16.4 ,  73.  ,  47.  ,  13.7 ,  12.6 ,  12.8 ,  22.1 ,  15.8 ,
        16.3 ,   9.7 ,   6.8 ,  35.  ,  31.7 , 100.  ,  23.  ,  88.4 ,
        29.8 ,  25.7 ,  77.4 ,  53.  ,  49.  ,  29.5 ,  33.  ,  37.5 ,
        69.  ,  59.  ,  19.2 ,  29.  ,   9.8 ,  20.35,  12.  ,  18.5 ,
         9.3 ,  11.6 ,  14.3 ,  10.8 ,   7.6 ,  20.5 ,  18.2 ,   9.  ,
         7.8 ,   5.7 ,  13.5 ,  11.5 ,  24.  ,  16.7 ,  21.4 ,  13.3 ,
         9.5 ,  12.1 ,  17.8 ,  27.2 ,   9.4 ,   5.8 ,  38.  ,   9.9 ,
        11.3 ,   6.7 ,  73.5 ,  79.8 ,  48.5 ,  39.8 ,  58.8 ,  26.5 ,
        13.4 ,  17.1 ,   8.9 ,  17.2 ,  16.9 ,  29.9 ,   9.6 ,  11.1 ,
      

In [11]:
erp["stock_quantity"].unique()

array([  0,  15,  34,  12,  66,  36,  22,  46,  41,  35,  16, 112, 267,
        73,  60,  10,  27,  65,  31, 157,  98,  28,  11,  50,  54,  53,
        48,  14,  37,  45,  24,  19,  26,  43,   7,   6,  42,   5,   1,
         8,  33,  18,  17,  57, 128,  70,  58, 167, 100,  94, 276, 109,
        47, 137,  90,  99, 209,  55,  13, 105, 190,  69,  89, 195, 578,
         2,  83, 180,  20,  49,  85, 141,  25,  64, 102,  21,  56,   4,
       133,   3,  96,   9,  61,  39, 237, 114, 106,  23,  32,  93, 161,
        30, 178,  29, 151, 140,  76,  97, 163,  62, 257, 284, 168, 143,
        92,  88,  44,  95, 289,  72, 203, 129,  38,  63, 130,  51, 123,
       118, 101,  84, 132, 211, 124, 120, 363, 192,  40,  91], dtype=int64)

- Outlier management :

In [12]:
erp_error = erp.loc[erp["stock_status"].isin(["instock"])].copy()

In [13]:
erp_error["stock_quantity"].unique()

array([ 15,  34,  12,  66,  36,  22,  46,  41,  35,  16, 112, 267,  73,
        60,  10,  27,  65,  31, 157,  98,  28,  11,  50,  54,  53,  48,
        14,  37,  45,  24,  19,  26,  43,   7,   6,  42,   5,   1,   8,
        33,  18,  17,  57, 128,  70,  58, 167, 100,  94, 276, 109,  47,
       137,  90,  99, 209,  55,  13, 105, 190,  69,  89, 195, 578,   2,
        83, 180,  20,  49,  85, 141,  25,  64, 102,  21,  56,   4, 133,
         3,  96,   9,  61,  39, 237, 114, 106,  23,  32,  93, 161,  30,
       178,  29, 151, 140,  76,  97, 163,  62, 257, 284, 168, 143,  92,
        88,  44,   0,  95, 289,  72, 203, 129,  38,  63, 130,  51, 123,
       118, 101,  84, 132, 211, 124, 120, 363, 192,  40,  91], dtype=int64)

In [14]:
erp_error1 = erp_error.loc[erp_error["stock_quantity"].isin([0])].copy()

In [15]:
erp_error1

product_id  onsale_web  price  stock_quantity stock_status
443        4954           1   25.0               0      instock

In [16]:
erp_error1.replace("instock","outofstock")

product_id  onsale_web  price  stock_quantity stock_status
443        4954           1   25.0               0   outofstock

 <a id='another_cell_b'></a>


### b. [web.csv](http://localhost:8888/edit/web.csv) : exploration and data cleaning*

- Loading file:

In [17]:
web = pd.read_csv('web.csv', sep=';')

- First 5 rows display :

In [18]:
web.head()

sku  virtual  downloadable  rating_count  average_rating  \
0  bon-cadeau-25-euros        0             0             0             0.0   
1                15298        0             0             0             0.0   
2                15296        0             0             0             0.0   
3                15300        0             0             0             0.0   
4                19814        0             0             0             0.0   

   total_sales tax_status  tax_class  post_author            post_date  ...  \
0         10.0    taxable        NaN          1.0  2018-06-01 13:53:46  ...   
1          6.0    taxable        NaN          2.0  2018-02-08 12:58:52  ...   
2          0.0    taxable        NaN          2.0  2018-02-08 13:49:41  ...   
3          0.0    taxable        NaN          2.0  2018-02-08 14:08:36  ...   
4          3.0    taxable        NaN          2.0  2018-02-09 14:01:05  ...   

                                           post_name        post_modified  \
0                             bon-cadeau-de-25-euros  2018-06-01 14:13:57   
1        pierre-jean-villa-saint-joseph-preface-2018  2019-12-30 09:30:29   
2          pierre-jean-villa-saint-joseph-tilde-2017  2019-12-21 09:00:17   
3  pierre-jean-villa-croze-hermitage-accroche-coe...  2020-06-26 18:15:03   
4                  pierre-jean-villa-igp-gamine-2018  2020-01-04 16:36:01   

     post_modified_gmt post_content_filtered post_parent  \
0  2018-06-01 12:13:57                   NaN         0.0   
1  2019-12-30 08:30:29                   NaN         0.0   
2  2019-12-21 08:00:17                   NaN         0.0   
3  2020-06-26 16:15:03                   NaN         0.0   
4  2020-01-04 15:36:01                   NaN         0.0   

                                                guid menu_order  post_type  \
0  https://www.bottle-neck.fr/?post_type=product&...        0.0    product   
1  https://www.bottle-neck.fr/?post_type=product&...        0.0    product   
2  https://www.bottle-neck.fr/?post_type=product&...        0.0    product   
3  https://www.bottle-neck.fr/?post_type=product&...        0.0    product   
4  https://www.bottle-neck.fr/?post_type=product&...        0.0    product   

  post_mime_type comment_count  
0            NaN           0.0  
1            NaN           0.0  
2            NaN           0.0  
3            NaN           0.0  
4            NaN           0.0  

[5 rows x 28 columns]

- Number of rows and columns :

In [19]:
web.shape

(1513, 28)

- .dtypes display :

In [20]:
web.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1513 entries, 0 to 1512
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   sku                    1428 non-null   object 
 1   virtual                1513 non-null   int64  
 2   downloadable           1513 non-null   int64  
 3   rating_count           1513 non-null   int64  
 4   average_rating         1430 non-null   float64
 5   total_sales            1430 non-null   float64
 6   tax_status             716 non-null    object 
 7   tax_class              0 non-null      float64
 8   post_author            1430 non-null   float64
 9   post_date              1430 non-null   object 
 10  post_date_gmt          1430 non-null   object 
 11  post_content           0 non-null      float64
 12  post_title             1430 non-null   object 
 13  post_excerpt           716 non-null    object 
 14  post_status            1430 non-null   object 
 15  comm

- new web df :

In [21]:
web["virtual"].unique()

array([0], dtype=int64)

In [22]:
web["downloadable"].unique()

array([0], dtype=int64)

In [23]:
web["rating_count"].unique()

array([0], dtype=int64)

In [24]:
web["average_rating"].unique()

array([ 0., nan])

In [25]:
web["tax_class"].unique()

array([nan])

In [26]:
web["post_content"].unique()

array([nan])

In [27]:
web["post_content_filtered"].unique()

array([nan])

In [28]:
web["post_parent"].unique()

array([ 0., nan])

In [29]:
web["menu_order"].unique()

array([ 0., nan])

In [30]:
web["comment_count"].unique()

array([ 0., nan])

In [31]:
web_new = web[{'sku','total_sales','tax_status','post_author','post_date','post_date_gmt','post_title','post_excerpt','post_status','comment_status','ping_status','post_password','post_name','post_modified','post_modified_gmt','guid','post_type','post_mime_type'}]

In [32]:
web_new.head()

post_mime_type                                               guid  \
0            NaN  https://www.bottle-neck.fr/?post_type=product&...   
1            NaN  https://www.bottle-neck.fr/?post_type=product&...   
2            NaN  https://www.bottle-neck.fr/?post_type=product&...   
3            NaN  https://www.bottle-neck.fr/?post_type=product&...   
4            NaN  https://www.bottle-neck.fr/?post_type=product&...   

             post_date post_status  post_password    post_modified_gmt  \
0  2018-06-01 13:53:46     publish            NaN  2018-06-01 12:13:57   
1  2018-02-08 12:58:52     publish            NaN  2019-12-30 08:30:29   
2  2018-02-08 13:49:41     publish            NaN  2019-12-21 08:00:17   
3  2018-02-08 14:08:36     publish            NaN  2020-06-26 16:15:03   
4  2018-02-09 14:01:05     publish            NaN  2020-01-04 15:36:01   

   total_sales        post_modified tax_status  post_author  \
0         10.0  2018-06-01 14:13:57    taxable          1.0   
1          6.0  2019-12-30 09:30:29    taxable          2.0   
2          0.0  2019-12-21 09:00:17    taxable          2.0   
3          0.0  2020-06-26 18:15:03    taxable          2.0   
4          3.0  2020-01-04 16:36:01    taxable          2.0   

                   sku ping_status post_type comment_status  \
0  bon-cadeau-25-euros      closed   product         closed   
1                15298      closed   product         closed   
2                15296      closed   product         closed   
3                15300      closed   product         closed   
4                19814      closed   product         closed   

                                           post_name        post_date_gmt  \
0                             bon-cadeau-de-25-euros  2018-06-01 11:53:46   
1        pierre-jean-villa-saint-joseph-preface-2018  2018-02-08 11:58:52   
2          pierre-jean-villa-saint-joseph-tilde-2017  2018-02-08 12:49:41   
3  pierre-jean-villa-croze-hermitage-accroche-coe...  2018-02-08 13:08:36   
4                  pierre-jean-villa-igp-gamine-2018  2018-02-09 13:01:05   

                                          post_title  \
0                                  Bon cadeau de 25€   
1        Pierre Jean Villa Saint-Joseph Préface 2018   
2    Pierre Jean Villa Saint-Joseph Rouge Tildé 2017   
3  Pierre Jean Villa Crozes-Hermitage Accroche Co...   
4  Pierre Jean Villa IGP Collines Rhodaniennes Ga...   

                                        post_excerpt  
0  <span style="color: #a85253;"><strong>Parlons ...  
1  Il exhale un nez subtil, racé avec du poivre f...  
2  Les vieilles vignes lui apportent une rare pro...  
3  Dentelle de fruit de jeunes syrah, aux tanins ...  
4  Gamine représente tout le fruité et la gourman...

In [33]:
web_new.shape

(1513, 18)

- New df "product" :

In [34]:
web_new_product = web_new.loc[web_new["post_type"].isin(["product"])].copy()

In [35]:
web_new_product

post_mime_type                                               guid  \
0              NaN  https://www.bottle-neck.fr/?post_type=product&...   
1              NaN  https://www.bottle-neck.fr/?post_type=product&...   
2              NaN  https://www.bottle-neck.fr/?post_type=product&...   
3              NaN  https://www.bottle-neck.fr/?post_type=product&...   
4              NaN  https://www.bottle-neck.fr/?post_type=product&...   
..             ...                                                ...   
762            NaN  https://www.bottle-neck.fr/?post_type=product&...   
767            NaN  https://www.bottle-neck.fr/?post_type=product&...   
768            NaN  https://www.bottle-neck.fr/?post_type=product&...   
797            NaN  https://www.bottle-neck.fr/?post_type=product&...   
798            NaN  https://www.bottle-neck.fr/?post_type=product&...   

               post_date post_status  post_password    post_modified_gmt  \
0    2018-06-01 13:53:46     publish            NaN  2018-06-01 12:13:57   
1    2018-02-08 12:58:52     publish            NaN  2019-12-30 08:30:29   
2    2018-02-08 13:49:41     publish            NaN  2019-12-21 08:00:17   
3    2018-02-08 14:08:36     publish            NaN  2020-06-26 16:15:03   
4    2018-02-09 14:01:05     publish            NaN  2020-01-04 15:36:01   
..                   ...         ...            ...                  ...   
762  2020-04-25 13:22:38     publish            NaN  2020-08-26 15:35:03   
767  2020-05-02 14:53:40     publish            NaN  2020-08-26 15:35:02   
768  2020-05-02 15:00:54     publish            NaN  2020-08-14 16:15:03   
797  2020-06-09 15:42:04     publish            NaN  2020-07-20 15:09:06   
798  2020-07-20 11:00:00     publish            NaN  2020-08-13 08:45:03   

     total_sales        post_modified tax_status  post_author  \
0           10.0  2018-06-01 14:13:57    taxable          1.0   
1            6.0  2019-12-30 09:30:29    taxable          2.0   
2            0.0  2019-12-21 09:00:17    taxable          2.0   
3            0.0  2020-06-26 18:15:03    taxable          2.0   
4            3.0  2020-01-04 16:36:01    taxable          2.0   
..           ...                  ...        ...          ...   
762          5.0  2020-08-26 17:35:03    taxable          2.0   
767          0.0  2020-08-26 17:35:02    taxable          2.0   
768          0.0  2020-08-14 18:15:03    taxable          2.0   
797          0.0  2020-07-20 17:09:06    taxable          2.0   
798          0.0  2020-08-13 10:45:03    taxable          2.0   

                     sku ping_status post_type comment_status  \
0    bon-cadeau-25-euros      closed   product         closed   
1                  15298      closed   product         closed   
2                  15296      closed   product         closed   
3                  15300      closed   product         closed   
4                  19814      closed   product         closed   
..                   ...         ...       ...            ...   
762                16135      closed   product         closed   
767                15891      closed   product         closed   
768                15887      closed   product         closed   
797              13127-1      closed   product         closed   
798                16230      closed   product         closed   

                                             post_name        post_date_gmt  \
0                               bon-cadeau-de-25-euros  2018-06-01 11:53:46   
1          pierre-jean-villa-saint-joseph-preface-2018  2018-02-08 11:58:52   
2            pierre-jean-villa-saint-joseph-tilde-2017  2018-02-08 12:49:41   
3    pierre-jean-villa-croze-hermitage-accroche-coe...  2018-02-08 13:08:36   
4                    pierre-jean-villa-igp-gamine-2018  2018-02-09 13:01:05   
..                                                 ...                  ...   
762                    mouthes-le-bihan-aime-chai-2015  2020-04-25 11:22:38   
767         camin-la

In [36]:
web_new_product.shape

(716, 18)

In [37]:
web_new_product.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 716 entries, 0 to 798
Data columns (total 18 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   post_mime_type     0 non-null      object 
 1   guid               716 non-null    object 
 2   post_date          716 non-null    object 
 3   post_status        716 non-null    object 
 4   post_password      0 non-null      float64
 5   post_modified_gmt  716 non-null    object 
 6   total_sales        716 non-null    float64
 7   post_modified      716 non-null    object 
 8   tax_status         716 non-null    object 
 9   post_author        716 non-null    float64
 10  sku                714 non-null    object 
 11  ping_status        716 non-null    object 
 12  post_type          716 non-null    object 
 13  comment_status     716 non-null    object 
 14  post_name          716 non-null    object 
 15  post_date_gmt      716 non-null    object 
 16  post_title         716 non

- New df "attachment" :

In [38]:
web_new_attachment = web_new.loc[web_new["post_type"].isin(["attachment"])].copy()

In [39]:
web_new_attachment

post_mime_type                                               guid  \
799      image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   
800      image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   
801      image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   
802      image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   
803      image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   
...             ...                                                ...   
1508     image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   
1509     image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   
1510     image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   
1511     image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   
1512     image/jpeg  https://www.bottle-neck.fr/wp-content/uploads/...   

                post_date post_status  post_password    post_modified_gmt  \
799   2018-02-08 12:58:52     publish            NaN  2019-12-30 08:30:29   
800   2018-02-08 13:49:41     publish            NaN  2019-12-21 08:00:17   
801   2018-02-08 14:08:36     publish            NaN  2020-06-26 16:15:03   
802   2018-02-09 14:01:05     publish            NaN  2020-01-04 15:36:01   
803   2018-02-12 09:04:37     publish            NaN  2020-01-04 15:36:10   
...                   ...         ...            ...                  ...   
1508  2020-04-25 13:22:38     publish            NaN  2020-08-26 15:35:03   
1509  2020-05-02 14:53:40     publish            NaN  2020-08-26 15:35:02   
1510  2020-05-02 15:00:54     publish            NaN  2020-08-14 16:15:03   
1511  2020-06-09 15:42:04     publish            NaN  2020-07-20 15:09:06   
1512  2020-07-20 11:00:00     publish            NaN  2020-08-13 08:45:03   

      total_sales        post_modified tax_status  post_author      sku  \
799           6.0  2019-12-30 09:30:29        NaN          2.0    15298   
800           0.0  2019-12-21 09:00:17        NaN          2.0    15296   
801           0.0  2020-06-26 18:15:03        NaN          2.0    15300   
802           3.0  2020-01-04 16:36:01        NaN          2.0    19814   
803           0.0  2020-01-04 16:36:10        NaN          2.0    19815   
...           ...                  ...        ...          ...      ...   
1508          5.0  2020-08-26 17:35:03        NaN          2.0    16135   
1509          0.0  2020-08-26 17:35:02        NaN          2.0    15891   
1510          0.0  2020-08-14 18:15:03        NaN          2.0    15887   
1511          0.0  2020-07-20 17:09:06        NaN          2.0  13127-1   
1512          0.0  2020-08-13 10:45:03        NaN          2.0    16230   

     ping_status   post_type comment_status  \
799       closed  attachment         closed   
800       closed  attachment         closed   
801       closed  attachment         closed   
802       closed  attachment         closed   
803       closed  attachment         closed   
...          ...         ...            ...   
1508      closed  attachment         closed   
1509      closed  attachment         closed   
1510      closed  attachment         closed   
1511      closed  attachment         closed   
1512      closed  attachment         closed   

                                              post_name        post_date_gmt  \
799         pierre-jean-villa-saint-joseph-preface-2018  2018-02-08 11:58:52   
800           pierre-jean-villa-saint-joseph-tilde-2017  2018-02-08 12:49:41   
801   pierre-jean-villa-croze-hermitage-accroche-coe...  2018-02-08 13:08:36   
802                   pierre-jean-villa-igp-gamine-2018  2018-02-09 13:01:05   
803           pierre-jean-villa-cote-rotie-carmina-2017  2018-02-12 08:04:37   
...                                                 ...                  ...   
1508                    mouthes-le-bihan-aime-chai-2015  2020-04-25 11:22:38   
1509         camin-larredya-jurancon-sec-la-virada-2018  2020-05-02 12:53:40   
1510 

In [40]:
web_new_attachment.shape

(714, 18)

  <a id='another_cell_c'></a>

### c. [liaison.csv](http://localhost:8888/edit/liaison.csv) : exploration and data cleaning


- Loading file:

In [41]:
liaison = pd.read_csv('liaison.csv', sep=';')

- First 5 rows display :

In [42]:
liaison.head()

product_id id_web
0        3847  15298
1        3849  15296
2        3850  15300
3        4032  19814
4        4039  19815

- Number of rows and columns :

In [43]:
liaison.shape

(825, 2)

- .dtypes display :

In [44]:
liaison.dtypes

product_id     int64
id_web        object
dtype: object

In [45]:
liaison.rename(columns = {"id_web": "sku"}, inplace=True)

In [46]:
liaison.head()

product_id    sku
0        3847  15298
1        3849  15296
2        3850  15300
3        4032  19814
4        4039  19815

In [47]:
web.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1513 entries, 0 to 1512
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype  
---  ------                 --------------  -----  
 0   sku                    1428 non-null   object 
 1   virtual                1513 non-null   int64  
 2   downloadable           1513 non-null   int64  
 3   rating_count           1513 non-null   int64  
 4   average_rating         1430 non-null   float64
 5   total_sales            1430 non-null   float64
 6   tax_status             716 non-null    object 
 7   tax_class              0 non-null      float64
 8   post_author            1430 non-null   float64
 9   post_date              1430 non-null   object 
 10  post_date_gmt          1430 non-null   object 
 11  post_content           0 non-null      float64
 12  post_title             1430 non-null   object 
 13  post_excerpt           716 non-null    object 
 14  post_status            1430 non-null   object 
 15  comm

 <a id='another_cell_d'></a>

### d. New df (merge)

In [48]:
df_liaison_web = liaison.merge(web_new_product, on="sku", how="inner")

In [49]:
df_liaison_web

product_id      sku post_mime_type  \
0          3847    15298            NaN   
1          3849    15296            NaN   
2          3850    15300            NaN   
3          4032    19814            NaN   
4          4039    19815            NaN   
..          ...      ...            ...   
891        6930    16135            NaN   
892        7023    15891            NaN   
893        7025    15887            NaN   
894        7247  13127-1            NaN   
895        7338    16230            NaN   

                                                  guid            post_date  \
0    https://www.bottle-neck.fr/?post_type=product&...  2018-02-08 12:58:52   
1    https://www.bottle-neck.fr/?post_type=product&...  2018-02-08 13:49:41   
2    https://www.bottle-neck.fr/?post_type=product&...  2018-02-08 14:08:36   
3    https://www.bottle-neck.fr/?post_type=product&...  2018-02-09 14:01:05   
4    https://www.bottle-neck.fr/?post_type=product&...  2018-02-12 09:04:37   
..                                                 ...                  ...   
891  https://www.bottle-neck.fr/?post_type=product&...  2020-04-25 13:22:38   
892  https://www.bottle-neck.fr/?post_type=product&...  2020-05-02 14:53:40   
893  https://www.bottle-neck.fr/?post_type=product&...  2020-05-02 15:00:54   
894  https://www.bottle-neck.fr/?post_type=product&...  2020-06-09 15:42:04   
895  https://www.bottle-neck.fr/?post_type=product&...  2020-07-20 11:00:00   

    post_status  post_password    post_modified_gmt  total_sales  \
0       publish            NaN  2019-12-30 08:30:29          6.0   
1       publish            NaN  2019-12-21 08:00:17          0.0   
2       publish            NaN  2020-06-26 16:15:03          0.0   
3       publish            NaN  2020-01-04 15:36:01          3.0   
4       publish            NaN  2020-01-04 15:36:10          0.0   
..          ...            ...                  ...          ...   
891     publish            NaN  2020-08-26 15:35:03          5.0   
892     publish            NaN  2020-08-26 15:35:02          0.0   
893     publish            NaN  2020-08-14 16:15:03          0.0   
894     publish            NaN  2020-07-20 15:09:06          0.0   
895     publish            NaN  2020-08-13 08:45:03          0.0   

           post_modified tax_status  post_author ping_status post_type  \
0    2019-12-30 09:30:29    taxable          2.0      closed   product   
1    2019-12-21 09:00:17    taxable          2.0      closed   product   
2    2020-06-26 18:15:03    taxable          2.0      closed   product   
3    2020-01-04 16:36:01    taxable          2.0      closed   product   
4    2020-01-04 16:36:10    taxable          2.0      closed   product   
..                   ...        ...          ...         ...       ...   
891  2020-08-26 17:35:03    taxable          2.0      closed   product   
892  2020-08-26 17:35:02    taxable          2.0      closed   product   
893  2020-08-14 18:15:03    taxable          2.0      closed   product   
894  2020-07-20 17:09:06    taxable          2.0      closed   product   
895  2020-08-13 10:45:03    taxable          2.0      closed   product   

    comment_status                                          post_name  \
0           closed        pierre-jean-villa-saint-joseph-preface-2018   
1           closed          pierre-jean-villa-saint-joseph-tilde-2017   
2           closed  pierre-jean-villa-croze-hermitage-accroche-coe...   
3           closed                  pierre-jean-villa-igp-gamine-2018   
4           closed          pierre-jean-villa-cote-rotie-carmina-2017   
..             ...                                                ...   
891         closed                    mouthes-le-bihan-aime-chai-2015   
892         closed         camin-larredya-jurancon-sec-la-virada-2018   
893         closed             jamet-cote-rotie-fructus-voluptas-2018   
894         closed     clos-du-mont-olivet-chateauneuf-du-pape-2007-2   
895         closed  domaine-sa

In [50]:
df_liaison_erp = liaison.merge(erp, on="product_id", how="inner")

In [51]:
df_liaison_erp

product_id      sku  onsale_web  price  stock_quantity stock_status
0          3847    15298           1   24.2               0   outofstock
1          3849    15296           1   34.3               0   outofstock
2          3850    15300           1   20.8               0   outofstock
3          4032    19814           1   14.1               0   outofstock
4          4039    19815           1   46.0               0   outofstock
..          ...      ...         ...    ...             ...          ...
820        7203      NaN           0   45.0              30      instock
821        7204      NaN           0   45.0               9      instock
822        7247  13127-1           1   54.8              23      instock
823        7329  14680-1           0   26.5              14      instock
824        7338    16230           1   16.3              45      instock

[825 rows x 6 columns]

In [59]:
df_web_erp = df_liaison_web.merge(df_liaison_erp, on="product_id", how="inner")

In [62]:
df_web_erp

product_id    sku_x post_mime_type  \
0          3847    15298            NaN   
1          3849    15296            NaN   
2          3850    15300            NaN   
3          4032    19814            NaN   
4          4039    19815            NaN   
..          ...      ...            ...   
891        6930    16135            NaN   
892        7023    15891            NaN   
893        7025    15887            NaN   
894        7247  13127-1            NaN   
895        7338    16230            NaN   

                                                  guid            post_date  \
0    https://www.bottle-neck.fr/?post_type=product&...  2018-02-08 12:58:52   
1    https://www.bottle-neck.fr/?post_type=product&...  2018-02-08 13:49:41   
2    https://www.bottle-neck.fr/?post_type=product&...  2018-02-08 14:08:36   
3    https://www.bottle-neck.fr/?post_type=product&...  2018-02-09 14:01:05   
4    https://www.bottle-neck.fr/?post_type=product&...  2018-02-12 09:04:37   
..                                                 ...                  ...   
891  https://www.bottle-neck.fr/?post_type=product&...  2020-04-25 13:22:38   
892  https://www.bottle-neck.fr/?post_type=product&...  2020-05-02 14:53:40   
893  https://www.bottle-neck.fr/?post_type=product&...  2020-05-02 15:00:54   
894  https://www.bottle-neck.fr/?post_type=product&...  2020-06-09 15:42:04   
895  https://www.bottle-neck.fr/?post_type=product&...  2020-07-20 11:00:00   

    post_status  post_password    post_modified_gmt  total_sales  \
0       publish            NaN  2019-12-30 08:30:29          6.0   
1       publish            NaN  2019-12-21 08:00:17          0.0   
2       publish            NaN  2020-06-26 16:15:03          0.0   
3       publish            NaN  2020-01-04 15:36:01          3.0   
4       publish            NaN  2020-01-04 15:36:10          0.0   
..          ...            ...                  ...          ...   
891     publish            NaN  2020-08-26 15:35:03          5.0   
892     publish            NaN  2020-08-26 15:35:02          0.0   
893     publish            NaN  2020-08-14 16:15:03          0.0   
894     publish            NaN  2020-07-20 15:09:06          0.0   
895     publish            NaN  2020-08-13 08:45:03          0.0   

           post_modified  ... comment_status  \
0    2019-12-30 09:30:29  ...         closed   
1    2019-12-21 09:00:17  ...         closed   
2    2020-06-26 18:15:03  ...         closed   
3    2020-01-04 16:36:01  ...         closed   
4    2020-01-04 16:36:10  ...         closed   
..                   ...  ...            ...   
891  2020-08-26 17:35:03  ...         closed   
892  2020-08-26 17:35:02  ...         closed   
893  2020-08-14 18:15:03  ...         closed   
894  2020-07-20 17:09:06  ...         closed   
895  2020-08-13 10:45:03  ...         closed   

                                             post_name        post_date_gmt  \
0          pierre-jean-villa-saint-joseph-preface-2018  2018-02-08 11:58:52   
1            pierre-jean-villa-saint-joseph-tilde-2017  2018-02-08 12:49:41   
2    pierre-jean-villa-croze-hermitage-accroche-coe...  2018-02-08 13:08:36   
3                    pierre-jean-villa-igp-gamine-2018  2018-02-09 13:01:05   
4            pierre-jean-villa-cote-rotie-carmina-2017  2018-02-12 08:04:37   
..                                                 ...                  ...   
891                    mouthes-le-bihan-aime-chai-2015  2020-04-25 11:22:38   
892         camin-larredya-jurancon-sec-la-virada-2018  2020-05-02 12:53:40   
893             jamet-cote-rotie-fructus-voluptas-2018  2020-05-02 13:00:54   
894     clos-du-mont-olivet-chateauneuf-du-pape-2007-2  2020-06-09 13:42:04   
895  domaine-saint-nicolas-fiefs-vendeens-blanc-les...  2020-07-20 09:00:00   

                                            post_title  \
0          Pierre Jean Villa Saint-Joseph Préface 2018   
1      Pierre Jean Villa Saint-Joseph Rouge Tildé 2017   
2    Pierre Jean Villa

#### a. Delete NaN values on "sku" column

In [69]:
df_web_erp.dropna(subset=['sku_x'], inplace=True)

In [72]:
df_web_erp.shape

(714, 24)

In [71]:
df_web_erp.nunique()

product_id           714
sku_x                714
post_mime_type         0
guid                 714
post_date            714
post_status            1
post_password          0
post_modified_gmt    587
total_sales           41
post_modified        587
tax_status             1
post_author            2
ping_status            1
post_type              1
comment_status         1
post_name            714
post_date_gmt        714
post_title           711
post_excerpt         677
sku_y                714
onsale_web             1
price                362
stock_quantity       126
stock_status           2
dtype: int64

#### b. Drop duplicates on "post_title" and "price" columns

In [82]:
df_web_erp.drop_duplicates({'post_title','price'}, inplace=True)

In [86]:
df_web_erp.shape

(712, 24)